### ISSUE TITLE
vscode clj-kondo extention throws NullPointerException

### ISSUE THREAD

**Issue by dukefong8** [borkdude/clj-kondo.lsp#12]
Hi, thank you very much for building clj-kondo. It's an awesome tool!

A small issue.

When editing shadow-cljs style ns :default, e.g. below snippet.

```
(ns lambda
  (:require
   ["aws-sdk" :default AWS]))
```

Stacktrace from vscode output window, and output window pops up every time there is another exception thrown (same stracktrace). I have to disable the extension because of this.

```
-- Welcome to clj-kondo v2020.12.12.
--
-- To configure clj-kondo, create a .clj-kondo directory in the root of your workspace and place a config.edn file in it.
-- Check out the configuration documentation here: https://github.com/borkdude/clj-kondo/blob/master/doc/config.md.
--
-- If you have questions, join the #clj-kondo channel on Clojurians slack.
-- Report issues at: https://github.com/borkdude/clj-kondo.
--
-- Happy linting!

[Info  - 3:16:05 PM] Clj-kondo language server loaded. Please report any issues to https://github.com/borkdude/clj-kondo.
[Error - 3:16:05 PM] java.lang.NullPointerException
	at clojure.lang.Numbers.ops(Numbers.java:1068)
	at clojure.lang.Numbers.dec(Numbers.java:145)
	at clj_kondo.lsp_server.impl.server$finding__GT_Diagnostic.invokeStatic(server.clj:73)
	at clj_kondo.lsp_server.impl.server$lint_BANG_$fn__11709.invoke(server.clj:137)
	at clojure.core$mapv$fn__8445.invoke(core.clj:6912)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
	at clojure.core$reduce.invokeStatic(core.clj:6827)
	at clojure.core$mapv.invokeStatic(core.clj:6903)
	at clj_kondo.lsp_server.impl.server$lint_BANG_.invokeStatic(server.clj:126)
	at clj_kondo.lsp_server.impl.server.LSPTextDocumentService.didOpen(server.clj:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by borkdude** [comment]
@FongHou Can you try the previous version of the plugin and see if it was introduced in the latest one?

**Comment by dukefong8** [comment]
Tried 2020.11.700 and 2020.10.100. Same problem.

Thanks!

**Comment by dukefong8** [comment]
btw, standalone binary works fine.

**Comment by borkdude** [comment]
@FongHou The issue is that somehow there is a finding without a row and column and the vscode plugin expects these to always be there:

```
$ clj-kondo --lint /tmp/foo.cljs
/tmp/foo.cljs::: warning: #'aws-sdk/AWS is referred but never used
/tmp/foo.cljs:3:5: warning: namespace aws-sdk is required but never used
linting took 47ms, errors: 0, warnings: 2
```

**Comment by borkdude** [comment]
@FongHou I just pushed an update to the VSCode marketplace which should fix this.

**Comment by dukefong8** [comment]
Thank you very much! Works great!

![image](https://user-images.githubusercontent.com/13973254/102667619-d1a2ce00-4157-11eb-8d6d-6688cbb0e851.png)
